name: AnsiDye CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install dependencies (if necessary)
    - name: Install CMake
      run: sudo apt-get install cmake

    - name: Configure the CMake project
      run: cmake -B build

    - name: Build the project
      run: cmake --build build

    - name: Check executable
      run: test -x ./build/AnsiDye
